name: Basic Push Workflow

on:
  push:    # Автоматический запуск при любом push

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: Вывод сообщения
        run: echo "Workflow запущен при Git push"
