# This is a basic workflow to help you get started with Actions

name: practice_number14

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  number1:
    runs-on: ubuntu-latest
    steps:
      - name: numbers_â„–1
        run: echo Hello, world!

  

